const baseUrl = 'http://169.254.171.85:8000/api';
const registerUrl = '$baseUrl/enregistrer';
const loginUrl = '$baseUrl/connexion';
const userUrl = '$baseUrl/user';
const logoutUrl = '$baseUrl/logout';
const vehiculeUrl = '$baseUrl/vehicule';
const annonceUrl = '$baseUrl/annonce';
const rechercherUrl = '$baseUrl/rechercher';
const reserverUrl = '$baseUrl/reserver/{id}';
const forgotUrl = '$baseUrl/forgot';
const resetUrl = '$baseUrl/reset';
const estActifUrl = '$baseUrl/estActif/{id}';
const updateAnnonceUrl = '$baseUrl/update/{id}';
const destroyAnnonceUrl = '$baseUrl/destroy/{id}';
const showAnnonceUrl = '$baseUrl/showAnnonce';

const serverError = 'Server error';
const unAuthorizided = 'unAuthorizided';
const someThingWentWrong = 'Something Went Wrong, try again!';
